# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="CompanyCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "company_coverage",
            },
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "coverage",
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Partially Claimed"),
                            (2, "Fully Claimed"),
                            (3, "Expired"),
                            (4, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                ("expiry_date", models.DateField()),
                (
                    "total_coverage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_covered",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.company",
                    ),
                ),
            ],
            options={
                "db_table": "policy",
            },
        ),
        migrations.CreateModel(
            name="PolicyCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.coverage",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.policy",
                    ),
                ),
            ],
            options={
                "db_table": "policy_coverage",
            },
        ),
    ]
