# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.patient"
            ),
        ),
        migrations.AddField(
            model_name="companycoverage",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="insurance.company"
            ),
        ),
        migrations.AddField(
            model_name="companycoverage",
            name="coverage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="insurance.coverage"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policycoverage",
            unique_together={("policy", "coverage")},
        ),
        migrations.AlterUniqueTogether(
            name="companycoverage",
            unique_together={("company", "coverage")},
        ),
    ]
