# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_total_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "prescription_total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reservation_total_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TREATMENT_IN_PROGRESS", "Treatment In Progress"),
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                        ],
                        default="TREATMENT_IN_PROGRESS",
                        max_length=50,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "bill",
            },
        ),
        migrations.CreateModel(
            name="BillCoveredTreatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("treatment_name", models.CharField(max_length=255)),
                (
                    "treatment_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covered_treatments",
                        to="bill.bill",
                    ),
                ),
            ],
            options={
                "db_table": "bill_covered_treatment",
            },
        ),
    ]
