# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "medicine",
            },
        ),
        migrations.CreateModel(
            name="MedicineQuantity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("fulfilled_quantity", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "medicine_quantity",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Waiting for Stock"),
                            (2, "Done"),
                            (3, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "prescription",
            },
        ),
    ]
