# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.patient"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.pharmacist",
            ),
        ),
        migrations.AddField(
            model_name="medicinequantity",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pharmacy.medicine"
            ),
        ),
        migrations.AddField(
            model_name="medicinequantity",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pharmacy.prescription"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicinequantity",
            unique_together={("medicine", "prescription")},
        ),
    ]
