# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "facility",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("date_in", models.DateField()),
                ("date_out", models.DateField()),
                (
                    "total_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("max_capacity", models.IntegerField()),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="ReservationFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospitalization.facility",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospitalization.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_facility",
            },
        ),
    ]
