# Generated by Django 4.2 on 2025-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.patient"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmenttreatment",
            unique_together={("appointment", "treatment")},
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "date")},
        ),
    ]
